---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: golang:1.14.3
    commands:
      - apt-get update && apt-get install cmake -y
      - make install-pkger
      - make build
  - name: publish-docker
    image: plugins/docker:18
    settings:
      dockerfile: Dockerfile
      repo: publicawesome/stakewatcher
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
    when:
      status: [success, failure]

---
kind: signature
hmac: c9d3c05556970091086c2378e493b72ccca2d60238cf8859afc982f720f98368

...
