name: Go

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: dependencies
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install -y postgresql
        sudo systemctl start postgresql

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: go dependencies
      run: |
        go install github.com/volatiletech/sqlboiler-sqlite3
        go install github.com/volatiletech/sqlboiler/v4

    - name: sqlboiler
      run: sqlboiler sqlite3

#    - name: Test
#      run: go test -v ./...
